scriptencoding utf-8
" ^^ Please leave the above line at the start of the file.
"
" Most recent update: 2009-11-03T14:17:49 CET

let g:name = 'Ulrik Bonde'
let g:mail = 'ulrikbonde@gmail.com'
let g:tex_flavor='latex'

set nocompatible
set autoindent
set history=50
set ruler
set viminfo='20,\"500
set wildmenu
set wildignore+=*.o,*~,.lo
set suffixes+=.info,.aux,.log,.dvi,.bbl,.out,.o,.lo,.pdf
set nowrap
set noinsertmode
set nonumber
"set smartindent
set cindent
set incsearch
set showmatch
set ignorecase
set smartcase
set magic
set backspace=indent,eol,start
set lazyredraw
set showfulltag
set omnifunc=1
set showcmd
set background=dark
set mouse=a
set title
set modeline
set nofoldenable
set hlsearch
set tags+=/home/bonde/.vim/commontags
set ttyfast
set mat=6

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

syntax on

" Set the statusline
set laststatus=2
set statusline=
set statusline+=%n\
set statusline+=%f\
set statusline+=\[%{strlen(&ft)?&ft:'none'},
set statusline+=%{&encoding},
set statusline+=%{&fileformat}]
set statusline+=%=
set statusline+=%-14.(%l,%c%V%)\ %<%P

if "" == &shell

  if executable("/bin/bash")
    set shell=/bin/bash

    if has("eval")
      let is_bash=1
    endif
  elseif executable("/bin/zsh")
    set shell=/bin/zsh
  endif

endif

" Encoding stuff
set enc=utf-8
set tenc=utf-8

" Always check for UTF-8 when trying to determine encodings.
if &fileencodings !~? "utf-8"
  set fileencodings+=utf-8
endif

" Make sure we have a sane fallback for encoding detection
set fileencodings+=default

if isdirectory(expand("$VIMRUNTIME/ftplugin"))
  filetype plugin on
  set grepprg=grep\ -nH\ $*
  filetype indent on
endif

if has("eval")

  function! <SID>UpdateRcHeader()
    let l:c=col(".")
    let l:l=line(".")
    1,10s-\(Most recent update:\).*-\="Most recent update: ".strftime("%c")-e
    call cursor(l:l, l:c)
  endfunction

  function! CleverTab()
    if strpart(getline('.'), 0, col('.') - 1) =~ '^\s*$'
      return "\<Tab>"
    else
      return "\<C-P>"
    endif
  endfunction

  function! CallInterpreter()
    if exists("b:interpreter")
      exec ("!".b:interpreter." %")
    endif
  endfun

endif

if has("autocmd")
  augroup content
    au!

    " In text files, limit the width of text to 78 characters
    autocmd BufNewFile,BufRead *.txt
          \ if &tw == 0 && ! exists("g:leave_my_textwidth_alone") |
          \     setlocal textwidth=78 |
          \ endif

    " Read the interpretter if present
    autocmd BufEnter *
          \ if match( getline(1) , '^\#!') == 0 |
          \     execute("let b:interpreter = getline(1)[2:]") |
          \ endif

    " When editing a file, always jump to the last cursor position
    autocmd BufReadPost !gitcommit
          \ if ! exists("g:leave_my_cursor_position_alone") |
          \     if line("'\"") > 0 && line ("'\"") <= line("$") |
          \         exe "normal g'\"" |
          \     endif |
          \ endif

  augroup END

  " Additional files
  autocmd BufWritePre *.sh  :call <SID>UpdateRcHeader()
  autocmd BufWritePre *vimrc  :call <SID>UpdateRcHeader()
  autocmd BufWritePre *zshrc :call <SID>UpdateRcHeader()

  autocmd FileType mail,human set nohlsearch formatoptions+=t textwidth=72 nomodeline
  "autocmd FileType css set smartindent
  "autocmd FileType html,css set noexpandtab tabstop=2

endif " has("autocmd")

" Mark tabs and spaces
if (&termencoding == "utf-8") || has("gui_running")
  if v:version >= 700
    set list listchars=tab:»·,trail:·,extends:…,nbsp:‗
  else
    set list listchars=tab:»·,trail:·,extends:…
  endif
else
  if v:version >= 700
    set list listchars=tab:>-,trail:.,extends:>,nbsp:_
  else
    set list listchars=tab:>-,trail:.,extends:>
  endif
endif

iabbrev xdate <c-r>=strftime("%d/%m/%y %H:%M:%S")<cr>
iabbrev cdate <c-r>=strftime("%d/%m/%y")<cr>

map Q gq
map <C-F6> :ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>
map <F5> :call CallInterpreter()<CR>
nnoremap <Space> <PageDown>
inoremap <Tab>	<C-R>=CleverTab()<CR>
inoremap <S-Tab> <Tab>

" Set colorscheme
if ($TERM == "rxvt-unicode")
  colorscheme inkpot
else
  colorscheme elflord
endif

if has("gui_gtk")
  "set guioptions-=m
  set guioptions+=c
  set guioptions-=T
  set guioptions-=l
  set guioptions-=L
  set guioptions-=r
  set guioptions-=R

  set guifont=Bitstream\ Vera\ Sans\ Mono\ 9
endif

" vim: set fenc=utf-8 tw=80 sw=2 sts=2 et :
