#!/bin/bash

DOTFILESDIR=$HOME/dotfiles/

if ["$OSTYPE" == "msys"]
then
    echo "Found Windows environment."
    #ln -s $DOTFILESDIR/vimconf/vim $HOME/.vim
    #ln -s $DOTFILESDIR/vimconf/vimrc $HOME/.vimrc
else if ["$OSTYPE" == "linux-gnu"]
then
    echo "Found Linux environment."
    $DOTFILESDIR/setup/setup_links.py

    if [ `lsb_release -is` == "Ubuntu" ]
    then
        # Check if pip is installed
        if ! command -v pip >/dev/null 2>&1
        then
            # We could not find pip, install it
            sudo apt-get install python-pip
        fi

        # Check if flake8 is installed
        if ! command -v flake8 >/dev/null 2>&1
        then
            sudo pip install flake8
        fi
    fi
else
    echo "Operating system could not be determined."
fi

$DOTFILESDIR/setup/setup_git.sh

cd $DOTFILESDIR

git submodule init
git submodule update
