#!/bin/bash

DOTFILESDIR=$HOME/dotfiles/

$DOTFILESDIR/setup/setup_links.py
$DOTFILESDIR/setup/setup_git.sh

cd $DOTFILESDIR

git submodule init
git submodule update

sudo apt-get install python-pip
sudo pip install flake8
